$schemaver: 2.1
repo_url: https://github.com/byu-oit/awsparams
software:
  - assignment_group: gro:AD-OIT Tools
    deploy_to_cmdb: true
    developed_by_byu: true
    links:
      system_documentation_url: https://github.com/byu-oit/awsparams
    maintained_by:
      - ndpete
      - pauldeden
    microservice: false
    name: awsparams
    notes:
    short_description: A simple CLI for adding/removing/renaming/copying AWS Param
      Store Parameters
    stages:
      production:
        aws_account: prd-appdev-oit-byu
        hosting_location: AWS
        relationships:
          supports:
            service:
              - Application Development
    technologies_used:
      - Python
      - AWS Systems Manager Parameter Store
      - Handel-Codepipeline
      - AWS CodeBuild
      - AWS CodePipeline
      - CircleCI.com
    type: command-line app
    data_sensitivity: public
    standard_change_template:
