version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements-dev.txt
  build:
    commands:
      - python moto-test.py
  post_build:
    commands:
artifacts:
  files:
    - '**/*'