version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands: 
  post_build:
    commands:
artifacts:
  files:
    - '**/*'