version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements-dev.txt
      # Moto mocking workaround
      # Create AWS directory for fake credentials and create dummy credential file
      - mkdir -p ~/.aws/
      - echo "[default]\naws_access_key_id = FakeKey\naws_secret_access_key = FakeKey\naws_session_token = FakeKey" > ~/.aws/credentials
  build:
    commands:
      - pytest
  post_build:
    commands:
artifacts:
  files:
    - '**/*'