version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: python -m pip install poetry && poetry install
      - run:
          name: Run Tests
          command: poetry run pytest -vvv

workflows:
  version: 2
  test:
    jobs:
      - test