version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run: pip install --user -r requirements-dev.txt
      - run: pip install --user -r requirements.txt
      - run: python -m pytest -vvv

workflows:
  version: 2
  test:
    jobs:
      - test